#!/bin/bash

# Guarda las credenciales de git de forma indefinida
git config credential.helper store

# Accion a relaizar si no existe el archivo
export action="Add"

# En caso de que el archivo ya exista indicamos que
# vamos a actualizar
[[ -f "$1" ]] && export action="Update"

# Creo el archivo como un script bash de linux
[[ ! -f "$1" ]] && echo '#!/bin/bash' > $1

# Se agregan permisos de ejecucion al script
chmod u+x $1

# Abro el nuevo archivo con nano
nano $1

# Agrego el archivo a git
git add $1

# Hago un commit con el nombre del script
git commit -m "$action $1 script"
git push
