#!/usr/bin/env bash
# Redirect index page to dr2d4.tech
sudo apt update
sudo apt -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me http:\/\/dr2d4.tech\/ permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
string_404="server_name _;\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$string_404/" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart
