#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=1
while [ $x -le 10 ]
do
	if [ $x == 4 ]
	then
		echo bad luck
		((x++))
	elif [ $x == 8 ]
	then
		echo good luck
		((x++))
	else
		echo Holberton School
		((x++))
	fi
done
