#!/usr/bin/env bash
# This script is displaying "Holberton School" 20 times
x=1
while [ $x -le 20 ]
do
	case $x in
		4)
			echo $x
			echo bad luck from China
			((x++))
			;;
		9)
			echo $x
			echo bad luck from Japan
			((x++))
			;;
		17)
			echo $x
			echo bad luck from Italy
			((x++))
	    		;;
    	esac

	echo $x
	((x++))
done
